services:
  ollama:
    image: ollama/ollama
    container_name: procrastinationbuddy-ollama
    volumes:
      - ./.volumes/ollama:/root/.ollama
    ports:
      - "11434:11434"

  db:
    image: postgres:17
    container_name: procrastinationbuddy-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: procrastinationbuddy-backend
    depends_on:
      - ollama
      - db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks
      POSTGRES_HOST: procrastinationbuddy-db
      POSTGRES_PORT: 5432
      OLLAMA_URL: http://procrastinationbuddy-ollama:11434
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: procrastinationbuddy-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://procrastinationbuddy-backend:5000
